---
- hosts: all
  become: yes
  tasks:
    - name: Install package
      apt:
        name: nginx
        state: present
    - name: Start service
      service:
        name: nginx
        state: started
